---
# Configure MySQL account for app user
# See http://docs.ansible.com/mysql_user_module.html for why both tasks are required
# User allowed hosts must be set before default hosts

- name: create mysql account for app and set password for user hosts
  mysql_user: name=app state=present password={{ mysqlsql_server_app_user_password }} host={{ item }}
  with_items: mysqlsql_server_user_allowed_hosts_app_user

- name: create mysql account for app and set password for default hosts
  mysql_user: name=app state=present password={{ mysqlsql_server_app_user_password }} host={{ item }}
  with_items: mysqlsql_server_default_allowed_hosts_app_user
