---
# Configure MySQL account for app user

- name: create mysql account for app
  mysql_user: name=app state=present password={{ mysqlsql_server_app_user_password }} host={{ item }}
  with_items: app_hosts
