---
# Install & Configure MySQL server

- name: install mysql server
  apt: update_cache=yes cache_valid_time=3600 pkg={{ item }} state=present # won't update if done under an hour ago
  with_items:
  - mysql-server
  - python-mysqldb # required for ansible to interface with database

- name: configure my.cnf
  template: src=etc/mysql/my.cnf.j2 dest=/etc/mysql/my.cnf.j2 owner=root group=root mode=600
  notify:
    - Restart MySQL

- name: remove mysql test database
  mysql_db: db=test state=absent

- include: root-user.yml
- include: controller-user.yml
- include: app-user.yml
- include: anonymous-user.yml
