---
# Configure MySQL account for root user
# See http://docs.ansible.com/mysql_user_module.html for why both tasks are required
# User allowed hosts must be set before default hosts

- name: set password for mysql root user
  mysql_user: name=root password={{ mysql_server_root_user_password }} priv=*.*:ALL,GRANT

- name: ensure correct root password is used
  template: src=root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: configure user defined allowed hosts for mysql root user
  mysql_user: name=root state=present host={{ item }}
  with_items: mysql_server_user_allowed_hosts_root_user

- name: create mysql root user for all mysql users defined allowed hosts
  mysql_user: name=root state=present host={{ item }}
  with_items: mysql_server_user_allowed_hosts_all_mysql_users

- name: configure root user default allowed hosts
  mysql_user: name=root state=present host={{ item }}
  with_items: mysql_server_default_allowed_hosts_root_user

- name: configure default allowed hosts for all users for root user
  mysql_user: name=root state=present host={{ item }}
  with_items: mysql_server_default_allowed_hosts_all_users
