---
# Configure MySQL account for root user
# see http://docs.ansible.com/mysql_user_module.html for why both tasks are required

- name: set mysql root password
  mysql_user: name=root password={{ mysqlsql_server_root_user_password }} host={{ item }} priv=*.*:ALL,GRANT
  with_items: mysqlsql_server_allowed_hosts_root_user

- name: ensure correct root password is used
  template: src=root/my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600
